---
name: Run ansible-lint

on: push

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup the python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install the pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Install dependent packages
        run: pipenv sync --dev

      - name: Run ansible-lint
        run: pipenv run ansible-lint --force-color playbooks
